# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-18 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_identy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identy',
            name='identy',
            field=models.CharField(max_length=20),
        ),
    ]
